server.port: 8071
spring:
  datasource:
    url: jdbc:h2:mem:acl-demo
    # tcp connection jdbc:h2:tcp://localhost:7072/mem:acl-demo
  jpa:
    hibernate:
      ddl-auto: none
  # Templates & Static resources reloading during development
#  thymeleaf:
#    prefix: file:src/main/resources/templates/
#    cache: false
#  resources:
#    static-locations: file:src/main/resources/static/
#    cache.period: 0
logging:
  level:
    org.springframework: info
